### ISSUE TITLE
有什么方式可以更好地跟进node的文档更新呢？

### ISSUE THREAD

**Issue by fengmk2** [sofish/node-api-docs#1]
如果还是以这种人工找出diff的方式，很难做成一个可持续维护和更新的中文文档。

大家有什么想法呢？fork node的项目？自动找出diff？

**Comment by sofish** [comment]
这个得好好想想，似乎还挺麻烦的。能想到的是，每次发布新版本的时候，给它的 docs 文件做次 diff（纯英文的上一版下一版），然后修改。
